<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>../../bin/</OutputPath>
  </PropertyGroup>

  <ItemGroup>

    <Compile Include="AssemblyInfo.fs" />
    <Compile Include="DictionaryExtensions.fs" />
    <Compile Include="Types.fs" />
    <Compile Include="NoobishFont.fs" />
    <Compile Include="InputState.fs" />
    <Compile Include="Caret.fs" />
    <Compile Include="Localization.fs" />
    <Compile Include="StyleSheet.fs" />
    <Compile Include="NoobishComponentsV2.fs" />
    <Compile Include="NoobishInputV2.fs" />
    <Compile Include="NoobishMeasureV2.fs" />
    <Compile Include="NoobishRenderV2.fs" />
    <Compile Include="NoobishLayoutV2.fs" />
    <Compile Include="NoobishV2.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="3.1.1" />
  </ItemGroup>

</Project>
